import { useState, useRef } from "react";
import { useSupabasePayrollRecords, type PayrollRecordWithEmployee } from "@/hooks/useSupabasePayroll";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { Input } from "@/components/ui/input";
import { Dialog, DialogContent, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { Separator } from "@/components/ui/separator";
import { Skeleton } from "@/components/ui/skeleton";
import { Search, Eye, CheckCircle, Trash2, Printer } from "lucide-react";
import { toast } from "sonner";

const fmt = (n: number) => "₱" + n.toLocaleString("en-PH", { minimumFractionDigits: 2 });

export default function Payslips() {
  const { records, loading, markAsPaid, deleteRecord } = useSupabasePayrollRecords();
  const [search, setSearch] = useState("");
  const [selected, setSelected] = useState<PayrollRecordWithEmployee | null>(null);
  const printRef = useRef<HTMLDivElement>(null);

  const filtered = records.filter((r) =>
    `${r.employees.first_name} ${r.employees.last_name} ${r.period}`.toLowerCase().includes(search.toLowerCase())
  );

  const handlePrint = () => {
    if (!printRef.current) return;
    const win = window.open("", "_blank");
    if (!win) return;
    win.document.write(`
      <html><head><title>Payslip</title>
      <style>
        body { font-family: 'Segoe UI', sans-serif; padding: 40px; color: #1a1a2e; }
        .header { text-align: center; margin-bottom: 24px; border-bottom: 2px solid #0891b2; padding-bottom: 16px; }
        .header h1 { font-size: 20px; margin: 0; color: #0891b2; }
        .header p { margin: 4px 0 0; font-size: 12px; color: #666; }
        .info { display: flex; justify-content: space-between; margin-bottom: 20px; font-size: 13px; }
        table { width: 100%; border-collapse: collapse; font-size: 13px; margin-bottom: 16px; }
        th, td { padding: 8px 12px; text-align: left; border-bottom: 1px solid #e5e7eb; }
        th { background: #f8fafc; font-weight: 600; }
        .right { text-align: right; }
        .total { font-weight: 700; font-size: 18px; text-align: center; padding: 16px; border: 2px solid #0891b2; border-radius: 8px; margin-top: 12px; color: #0891b2; }
        .footer { margin-top: 40px; font-size: 11px; color: #999; text-align: center; }
      </style></head><body>
      ${printRef.current.innerHTML}
      <div class="footer">Generated by PayrollPro • ${new Date().toLocaleDateString()}</div>
      </body></html>`);
    win.document.close();
    win.print();
  };

  if (loading) {
    return (
      <div className="animate-fade-in space-y-6">
        <div><h1 className="text-2xl font-bold text-foreground">Payslips</h1></div>
        <Skeleton className="h-96 rounded-xl" />
      </div>
    );
  }

  return (
    <div className="animate-fade-in space-y-6">
      <div>
        <h1 className="text-2xl font-bold text-foreground">Payslips</h1>
        <p className="text-sm text-muted-foreground">{records.length} total records</p>
      </div>

      <Card className="shadow-card">
        <CardHeader className="pb-3">
          <div className="relative max-w-sm">
            <Search className="absolute left-3 top-1/2 h-4 w-4 -translate-y-1/2 text-muted-foreground" />
            <Input className="pl-9" placeholder="Search payslips..." value={search} onChange={(e) => setSearch(e.target.value)} />
          </div>
        </CardHeader>
        <CardContent>
          {filtered.length === 0 ? (
            <p className="py-12 text-center text-sm text-muted-foreground">No payslips found. Run payroll first to generate records.</p>
          ) : (
            <Table>
              <TableHeader>
                <TableRow>
                  <TableHead>Employee</TableHead>
                  <TableHead>Period</TableHead>
                  <TableHead className="text-right">Gross</TableHead>
                  <TableHead className="text-right">Deductions</TableHead>
                  <TableHead className="text-right">Net Pay</TableHead>
                  <TableHead>Status</TableHead>
                  <TableHead className="text-right">Actions</TableHead>
                </TableRow>
              </TableHeader>
              <TableBody>
                {filtered.map((r) => (
                  <TableRow key={r.id}>
                    <TableCell className="font-medium">{r.employees.first_name} {r.employees.last_name}</TableCell>
                    <TableCell>{r.period}</TableCell>
                    <TableCell className="text-right font-mono text-sm">{fmt(Number(r.gross_pay))}</TableCell>
                    <TableCell className="text-right font-mono text-sm">{fmt(Number(r.total_deductions))}</TableCell>
                    <TableCell className="text-right font-mono text-sm font-semibold">{fmt(Number(r.net_pay))}</TableCell>
                    <TableCell>
                      <Badge variant={r.status === "paid" ? "default" : "secondary"} className={r.status === "paid" ? "bg-success text-success-foreground" : ""}>
                        {r.status}
                      </Badge>
                    </TableCell>
                    <TableCell className="text-right">
                      <div className="flex justify-end gap-1">
                        <Button variant="ghost" size="icon" onClick={() => setSelected(r)}><Eye className="h-4 w-4" /></Button>
                        {r.status === "processed" && (
                          <Button variant="ghost" size="icon" onClick={async () => { await markAsPaid(r.id); toast.success("Marked as paid"); }}>
                            <CheckCircle className="h-4 w-4 text-success" />
                          </Button>
                        )}
                        <Button variant="ghost" size="icon" onClick={async () => { await deleteRecord(r.id); toast.success("Record deleted"); }} className="text-destructive hover:text-destructive">
                          <Trash2 className="h-4 w-4" />
                        </Button>
                      </div>
                    </TableCell>
                  </TableRow>
                ))}
              </TableBody>
            </Table>
          )}
        </CardContent>
      </Card>

      <Dialog open={!!selected} onOpenChange={() => setSelected(null)}>
        <DialogContent className="max-w-md">
          <DialogHeader>
            <DialogTitle className="flex items-center justify-between">
              Digital Payslip
              <Button variant="outline" size="sm" onClick={handlePrint}><Printer className="mr-2 h-3.5 w-3.5" />Print</Button>
            </DialogTitle>
          </DialogHeader>
          {selected && (
            <div ref={printRef}>
              <div style={{ textAlign: "center", borderBottom: "2px solid hsl(199, 89%, 38%)", paddingBottom: 12, marginBottom: 16 }}>
                <h1 style={{ fontSize: 18, margin: 0, color: "hsl(199, 89%, 38%)" }}>PayrollPro</h1>
                <p style={{ margin: "4px 0 0", fontSize: 12, color: "#666" }}>School Payroll Management System</p>
              </div>
              <div className="flex justify-between text-sm mb-4">
                <div>
                  <p className="font-semibold text-foreground">{selected.employees.first_name} {selected.employees.last_name}</p>
                  <p className="text-xs text-muted-foreground">{selected.employees.position} • {selected.employees.department}</p>
                  <p className="text-xs text-muted-foreground">ID: {selected.employees.employee_id}</p>
                </div>
                <div className="text-right">
                  <p className="font-semibold text-foreground">{selected.period}</p>
                  <p className="text-xs text-muted-foreground">{new Date(selected.created_at).toLocaleDateString()}</p>
                </div>
              </div>
              <Separator className="mb-3" />
              <div className="space-y-2 text-sm">
                <Row label="Basic Salary" value={fmt(Number(selected.basic_salary))} />
                <Row label="Allowances" value={fmt(Number(selected.allowances))} />
                <Row label="Overtime" value={fmt(Number(selected.overtime))} />
                <Separator />
                <Row label="Gross Pay" value={fmt(Number(selected.gross_pay))} bold />
              </div>
              <div className="mt-3 rounded-lg bg-muted/50 p-3">
                <p className="mb-2 text-xs font-medium text-muted-foreground">DEDUCTIONS</p>
                <div className="space-y-1.5 text-sm">
                  {(selected.deductions as any[])?.map((d: any) => (
                    <Row key={d.name} label={d.name} value={`- ${fmt(d.amount)}`} />
                  ))}
                  <Separator />
                  <Row label="Total Deductions" value={fmt(Number(selected.total_deductions))} bold />
                </div>
              </div>
              <div className="mt-4 rounded-lg border-2 border-primary/20 bg-primary/5 p-4 text-center">
                <p className="text-xs text-muted-foreground">NET PAY</p>
                <p className="text-2xl font-bold text-primary">{fmt(Number(selected.net_pay))}</p>
              </div>
            </div>
          )}
        </DialogContent>
      </Dialog>
    </div>
  );
}

function Row({ label, value, bold }: { label: string; value: string; bold?: boolean }) {
  return (
    <div className={`flex justify-between ${bold ? "font-semibold" : ""}`}>
      <span className="text-muted-foreground">{label}</span>
      <span className="font-mono text-foreground">{value}</span>
    </div>
  );
}
